### ISSUE TITLE
block load dxffile error 

### ISSUE THREAD

**Issue by yonghuairuogu** [haplokuon/netDxf#116]
i want insert a entire dxf file to  another dxf file, when i load the dxffile as block,it appear the message ":“Closed polylines cannot be combined with other entities to make a hatch boundary path.”"

Block block = Block.Load(symblodxf);
 Insert insert = new Insert(block , new Vector2(Y, X));
dxf.AddEntity(insert);

[4302.zip](https://github.com/haplokuon/netDxf/files/3441055/4302.zip)

**Comment by haplokuon** [comment]
The origin of this problem is that associated hatches are not supported when its boundary path is made of intersected entities. This requires to calculate the intersection points between the different entities, something that is not implemented.

At the moment you have two choices, make your hatches non-associative or make sure that the associated entities correspond to the actual boundary path of the hatch.

I will try to make a fix so at least that error does not appear, like when it is loaded as a document. It will still be useful even though if the internal data of the hatch needs to be updated the resulting file might give problems when loaded elsewhere.

**Comment by yonghuairuogu** [comment]
I would appreciate it if you could fix  this program.because this file is a symbol of pipeline ,and it is formulated by institute, i cannot change its  composition.

**Comment by haplokuon** [comment]
Try it now with the latest code, you will need to compile it. The block will be created, even thought any Hatch entity will have its associative property set to false.
