### ISSUE TITLE
How to set default ZOOM EXTENT?

### ISSUE THREAD

**Issue by WangJi** [haplokuon/netDxf#20]
Hi, I've successfully created a dxf file.
But the question is I can't find a way to set **view extent**, here is what I'm trying:

    var dxf = new DxfDocument();
    var layout = dxf.Layouts.First();
    layout.MinExtents = new Vector3(minX, minY, 0);
    layout.MaxExtents = new Vector3(maxX, maxY, 0);
    layout.MinLimit = new Vector2(minX, minY);
    layout.MaxLimit = new Vector2(maxX, maxY);
    dxf.Save(savePath);

However, nothing changes.  Any help is **appreciated**.

--------
PS: I'm viewing dxf file on ***AutoCAD 2017***.

**Comment by WangJi** [comment]
Well, after a little digging, I found `dxf.Viewport.ViewCenter` is the key to view center.
Then where is the another `zoom level` key?
 `dxf.Viewport.ViewAspectRatio`  seems to take effect. Can anyone explain.

**Comment by haplokuon** [comment]
I cannot help you about it, the dxf documentation leaves too many things unclear. Those are the variables, perhaps there are other, that supposedly control the view but I have not been able to find how exactly how they work. My fear, and this is pure expeculation I might be wrong, they are related with the view in the user interface, but the size of the window where the entities are displayed is not saved in the dxf.

The best way to deal with it is in your own code that shows the contents of the file. Once the file is loaded you can calculate the size of the projected vertices and scale the bounding rectangle to fit the window in you user interface.

Since I am mostly interested in the actual geometry I do not care too much about this. Any program, where you load the file, will have some kind command to make a zoom extent.

Daniel

**Comment by WangJi** [comment]
That's totally cool.
Finally I manage to get things done by setting some magic number, haha.
Just as you said, we are only focused on generating vector file, for those who open it, why don't they just press `z  + e`.

**Comment by WangJi** [comment]
By the way, I think I should let know that I'm working on a program that converts a `handwriting` image from raster to vector. The input picture is like this: 
![image](https://user-images.githubusercontent.com/5742670/35107164-3a02fe92-fcab-11e7-863b-b047fb4657e8.png)
And with the help of your awesome work, I now can easily export those converted results into `dxf` file like this:
![image](https://user-images.githubusercontent.com/5742670/35107271-7a5644e0-fcab-11e7-9ec1-5fce996a050a.png)
Which saved me a lot of time at least a a week or more.
