### ISSUE TITLE
Aci color map not exactly the same with autocad

### ISSUE THREAD

**Issue by Wzshun** [haplokuon/netDxf#204]
In the map 99, 109, 119 and so on, each color index map are different from mine autocad(2012).
Such as index 99 is (19, 88, 19), while in the code is (19, 38, 19).

Is autocad version changes ? or code write wrong, since it seems that all 38 are 88.
Thanks.

**Comment by haplokuon** [comment]
It is possible that some index color do not exactly correspond to the rgb values in AutoCad, You can easly change the values in the IReadOnlyDictionary dictionary of the AciColor class. I wrote that table very long time ago and I remember having to change it due to updates with AutoCad. For example in [this list](https://gohtx.com/acadcolors.php) the index 99 has the rgb values (53, 79, 53), but that list seems very old. I tested that index 99 in AutoCad 2018 and its rgb values are (19, 38, 19) that one is correct, for indexes 109 and 119 you are correct the 38 should be a 88.

So, yes the values in the code can be wrong and, yes, the rgb values has changed in the past.

You might take a look at [this pull request](https://github.com/haplokuon/netDxf/pull/175) but the user is not giving any explanation about its code.
