### ISSUE TITLE
dxf Load Exception

### ISSUE THREAD

**Issue by spass2000** [haplokuon/netDxf#35]
Hello

i get an exception on loading a dxf file, because the WidthFactor is set to 300. it's possible to ignore such errors on loading?

rgds

public double WidthFactor
        {
            get { return this.widthFactor; }
            set
            {
                if (value < 0.01 || value > 100.0)
                    throw new ArgumentOutOfRangeException(nameof(value), value, "The Text width factor valid values range from 0.01 to 100.");
                this.widthFactor = value;
            }
        }

or

if (degree < 1 || degree > 10)
                throw new ArgumentOutOfRangeException(nameof(degree), degree, "The spline degree valid values range from 1 to 10.");

**Comment by haplokuon** [comment]
If an out of range value of the WidthFactor of a TextStyle, like in many other similar parameters, is found during while loading a file, the default 1.0 will be used instead. Is your netDxf up to date?

If you are curious check the DxfReader class source code, for the case 41 of the TextStyle read method (line 1955) the default value 1.0 is given for an out of range width factor.
```c#
case 41:
    widthFactor = this.chunk.ReadDouble();
    if (widthFactor < 0.01 || widthFactor > 100.0)
        widthFactor = 1.0;
    this.chunk.Next();
    break;
```

The last case you showed about the spline degree is a worse scenario, if the degree of the spline is out of range you cannot just give the default value of 3, since the list of control points and/or knot values will not correlate.

Daniel
