### ISSUE TITLE
The LinetypeShepeSegment scale must be greater than zero.

### ISSUE THREAD

**Issue by PetrMahdalicek** [haplokuon/netDxf#59]
Hello daniel, 
can you please have a look at this file.
[test2.zip](https://github.com/haplokuon/netDxf/files/2352686/test2.zip)

Net dxf 2.2 throws exception when loading this file. It says that scale of segment can not be 0. I opened that file using bricscad but I do not see what is wrong there. Also both BricsCAD an AutoCAD can open this file. 

thank you
Petr

**Comment by haplokuon** [comment]
Please upload a text based dxf not binary and don't see any complex linetype in your drawing and since it is binary I cannot take a look at its content.

Nevertheless, negative values, even zero (I would not recommend to use it) are allowed. If you need a quick fix just delete the ArgumentOutOfRangeException from the Scale property of the LinetypeShapeSegment and LinetypeTextSegment classes.

**Comment by PetrMahdalicek** [comment]
Thank you. If it helps you, here is text dxf file:
[test2.zip](https://github.com/haplokuon/netDxf/files/2369304/test2.zip)
