### ISSUE TITLE
Could not load .pat file for hatch

### ISSUE THREAD

**Issue by jkoehoorn** [haplokuon/netDxf#63]
Because my culture settings have a comma as decimal separator i'm not able to load a .pat file.
The fix is simple: add a Culture provider (part of HatchPattern.cs)  

IFormatProvider Provider = CultureInfo.InvariantCulture;
Vector2 origin = new Vector2(double.Parse(tokens[1], Provider), double.Parse(tokens[2], Provider));
Vector2 delta = new Vector2(double.Parse(tokens[3], Provider), double.Parse(tokens[4], Provider));

**Comment by haplokuon** [comment]
Yes, I am aware, LIN files also suffer the same problem. But even with PAT files fixed, for reasons unknown, AutoCad doesn't seems to like to load them. I do not know if I am doing something wrong or it is the version I tried, sometimes it is hard to test it since I do not always have access to it. Every time I try it keeps saying "Error in Pattern File", it does not even like to load a copy of its files.

In any case soon I will upload a fix for that and a few other things.
